project:
  type: website
  output-dir: _site

website:
  title: "External Sidebar Example"
  navbar:
    pinned: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About the Team"
        href: about/index.qmd
      - text: "Blog"
        href: blog/index.qmd

format:
  html:
    theme: cosmo

metadata-files:
  - sidebar_about.yml
  - sidebar_blog.yml